/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KanjiMastery = IDL.Record({
  'wrongCount' : IDL.Nat,
  'lastCorrect' : IDL.Int,
  'lastWrong' : IDL.Int,
  'masteryLevel' : IDL.Nat,
  'seenCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'kanji' : IDL.Text,
  'lastSeen' : IDL.Int,
});
export const RadicalMastery = IDL.Record({
  'wrongCount' : IDL.Nat,
  'radical' : IDL.Text,
  'masteryLevel' : IDL.Nat,
  'seenCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
});
export const WeakItem = IDL.Record({
  'itemId' : IDL.Text,
  'wrongCount' : IDL.Nat,
  'masteryLevel' : IDL.Nat,
  'itemType' : IDL.Text,
  'correctCount' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const KanjiDashboardStats = IDL.Record({
  'total' : IDL.Nat,
  'intermediate' : IDL.Nat,
  'strongItems' : IDL.Vec(WeakItem),
  'mastered' : IDL.Nat,
  'learning' : IDL.Nat,
  'weakItems' : IDL.Vec(WeakItem),
  'highFrequency' : IDL.Nat,
  'untouched' : IDL.Nat,
});
export const MasteryStatus = IDL.Variant({
  'Learning' : IDL.Null,
  'Untouched' : IDL.Null,
  'Intermediate' : IDL.Null,
  'Mastered' : IDL.Null,
});
export const KanjiMasteryPublic = IDL.Record({
  'status' : MasteryStatus,
  'wrongCount' : IDL.Nat,
  'lastCorrect' : IDL.Int,
  'lastWrong' : IDL.Int,
  'masteryLevel' : IDL.Nat,
  'seenCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'lookupCount' : IDL.Nat,
  'kanjiId' : IDL.Text,
  'lastSeen' : IDL.Int,
});
export const QuizAnalytics = IDL.Record({
  'totalCorrect' : IDL.Nat,
  'totalQuizzes' : IDL.Nat,
  'totalWrong' : IDL.Nat,
  'accuracy' : IDL.Float64,
});
export const RadicalDashboardStats = IDL.Record({
  'total' : IDL.Nat,
  'intermediate' : IDL.Nat,
  'mastered' : IDL.Nat,
  'learning' : IDL.Nat,
  'weakItems' : IDL.Vec(WeakItem),
  'untouched' : IDL.Nat,
});
export const RadicalMasteryPublic = IDL.Record({
  'status' : MasteryStatus,
  'wrongCount' : IDL.Nat,
  'radicalId' : IDL.Text,
  'masteryLevel' : IDL.Nat,
  'seenCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'lastSeen' : IDL.Int,
});
export const ScoreSummary = IDL.Record({
  'overallN4ReadinessScore' : IDL.Nat,
  'kanjiScore' : IDL.Nat,
  'vocabularyScore' : IDL.Nat,
  'radicalScore' : IDL.Nat,
  'readingScore' : IDL.Nat,
});
export const VocabDashboardStats = IDL.Record({
  'total' : IDL.Nat,
  'intermediate' : IDL.Nat,
  'strongItems' : IDL.Vec(WeakItem),
  'mastered' : IDL.Nat,
  'learning' : IDL.Nat,
  'weakItems' : IDL.Vec(WeakItem),
  'highFrequency' : IDL.Nat,
  'untouched' : IDL.Nat,
});
export const VocabMasteryPublic = IDL.Record({
  'status' : MasteryStatus,
  'wrongCount' : IDL.Nat,
  'lastCorrect' : IDL.Int,
  'lastWrong' : IDL.Int,
  'masteryLevel' : IDL.Nat,
  'seenCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'lookupCount' : IDL.Nat,
  'vocabId' : IDL.Text,
  'lastSeen' : IDL.Int,
});
export const ReadingSessionPublic = IDL.Record({
  'kanjiFailures' : IDL.Vec(IDL.Text),
  'wordsLookedUp' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'unknownWords' : IDL.Vec(IDL.Text),
});
export const AdaptiveQuizRatio = IDL.Record({
  'kanjiPercent' : IDL.Nat,
  'vocabularyPercent' : IDL.Nat,
  'radicalPercent' : IDL.Nat,
});
export const AdaptiveQuizSessionPublic = IDL.Record({
  'completedAt' : IDL.Opt(IDL.Int),
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'sessionId' : IDL.Text,
  'ratio' : AdaptiveQuizRatio,
});

export const idlService = IDL.Service({
  'completeAdaptiveSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'getAllKanjiMastery' : IDL.Func([], [IDL.Vec(KanjiMastery)], ['query']),
  'getAllRadicalMastery' : IDL.Func([], [IDL.Vec(RadicalMastery)], ['query']),
  'getDokkaiPriorityKanji' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getKanjiDashboard' : IDL.Func([], [KanjiDashboardStats], ['query']),
  'getKanjiMastery' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(KanjiMasteryPublic)],
      ['query'],
    ),
  'getKanjiMasteryByChar' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(KanjiMastery)],
      ['query'],
    ),
  'getQuizAnalytics' : IDL.Func([], [QuizAnalytics], ['query']),
  'getRadicalDashboard' : IDL.Func([], [RadicalDashboardStats], ['query']),
  'getRadicalMastery' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RadicalMasteryPublic)],
      ['query'],
    ),
  'getRadicalMasteryByChar' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RadicalMastery)],
      ['query'],
    ),
  'getScoreSummary' : IDL.Func([], [ScoreSummary], ['query']),
  'getUntouchedKanji' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getVocabDashboard' : IDL.Func([], [VocabDashboardStats], ['query']),
  'getVocabMastery' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VocabMasteryPublic)],
      ['query'],
    ),
  'getWeakKanji' : IDL.Func([IDL.Nat], [IDL.Vec(WeakItem)], ['query']),
  'getWeakKanjiByThreshold' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(KanjiMastery)],
      ['query'],
    ),
  'getWeakRadicals' : IDL.Func([IDL.Nat], [IDL.Vec(WeakItem)], ['query']),
  'getWeakVocab' : IDL.Func([IDL.Nat], [IDL.Vec(WeakItem)], ['query']),
  'listKanjiMastery' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(KanjiMasteryPublic)],
      ['query'],
    ),
  'listReadingSessions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ReadingSessionPublic)],
      ['query'],
    ),
  'recordQuizResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'saveReadingSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'startAdaptiveSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [AdaptiveQuizSessionPublic],
      [],
    ),
  'trackKanjiCorrect' : IDL.Func([IDL.Text], [], []),
  'trackKanjiLookup' : IDL.Func([IDL.Text], [], []),
  'trackKanjiSeen' : IDL.Func([IDL.Text], [], []),
  'trackKanjiWrong' : IDL.Func([IDL.Text], [], []),
  'trackRadicalCorrect' : IDL.Func([IDL.Text], [], []),
  'trackRadicalSeen' : IDL.Func([IDL.Text], [], []),
  'trackRadicalWrong' : IDL.Func([IDL.Text], [], []),
  'trackVocabCorrect' : IDL.Func([IDL.Text], [], []),
  'trackVocabLookup' : IDL.Func([IDL.Text], [], []),
  'trackVocabSeen' : IDL.Func([IDL.Text], [], []),
  'trackVocabWrong' : IDL.Func([IDL.Text], [], []),
  'updateKanjiMastery' : IDL.Func([IDL.Text, IDL.Bool], [KanjiMastery], []),
  'updateRadicalMastery' : IDL.Func([IDL.Text, IDL.Bool], [RadicalMastery], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KanjiMastery = IDL.Record({
    'wrongCount' : IDL.Nat,
    'lastCorrect' : IDL.Int,
    'lastWrong' : IDL.Int,
    'masteryLevel' : IDL.Nat,
    'seenCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'kanji' : IDL.Text,
    'lastSeen' : IDL.Int,
  });
  const RadicalMastery = IDL.Record({
    'wrongCount' : IDL.Nat,
    'radical' : IDL.Text,
    'masteryLevel' : IDL.Nat,
    'seenCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
  });
  const WeakItem = IDL.Record({
    'itemId' : IDL.Text,
    'wrongCount' : IDL.Nat,
    'masteryLevel' : IDL.Nat,
    'itemType' : IDL.Text,
    'correctCount' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const KanjiDashboardStats = IDL.Record({
    'total' : IDL.Nat,
    'intermediate' : IDL.Nat,
    'strongItems' : IDL.Vec(WeakItem),
    'mastered' : IDL.Nat,
    'learning' : IDL.Nat,
    'weakItems' : IDL.Vec(WeakItem),
    'highFrequency' : IDL.Nat,
    'untouched' : IDL.Nat,
  });
  const MasteryStatus = IDL.Variant({
    'Learning' : IDL.Null,
    'Untouched' : IDL.Null,
    'Intermediate' : IDL.Null,
    'Mastered' : IDL.Null,
  });
  const KanjiMasteryPublic = IDL.Record({
    'status' : MasteryStatus,
    'wrongCount' : IDL.Nat,
    'lastCorrect' : IDL.Int,
    'lastWrong' : IDL.Int,
    'masteryLevel' : IDL.Nat,
    'seenCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'lookupCount' : IDL.Nat,
    'kanjiId' : IDL.Text,
    'lastSeen' : IDL.Int,
  });
  const QuizAnalytics = IDL.Record({
    'totalCorrect' : IDL.Nat,
    'totalQuizzes' : IDL.Nat,
    'totalWrong' : IDL.Nat,
    'accuracy' : IDL.Float64,
  });
  const RadicalDashboardStats = IDL.Record({
    'total' : IDL.Nat,
    'intermediate' : IDL.Nat,
    'mastered' : IDL.Nat,
    'learning' : IDL.Nat,
    'weakItems' : IDL.Vec(WeakItem),
    'untouched' : IDL.Nat,
  });
  const RadicalMasteryPublic = IDL.Record({
    'status' : MasteryStatus,
    'wrongCount' : IDL.Nat,
    'radicalId' : IDL.Text,
    'masteryLevel' : IDL.Nat,
    'seenCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'lastSeen' : IDL.Int,
  });
  const ScoreSummary = IDL.Record({
    'overallN4ReadinessScore' : IDL.Nat,
    'kanjiScore' : IDL.Nat,
    'vocabularyScore' : IDL.Nat,
    'radicalScore' : IDL.Nat,
    'readingScore' : IDL.Nat,
  });
  const VocabDashboardStats = IDL.Record({
    'total' : IDL.Nat,
    'intermediate' : IDL.Nat,
    'strongItems' : IDL.Vec(WeakItem),
    'mastered' : IDL.Nat,
    'learning' : IDL.Nat,
    'weakItems' : IDL.Vec(WeakItem),
    'highFrequency' : IDL.Nat,
    'untouched' : IDL.Nat,
  });
  const VocabMasteryPublic = IDL.Record({
    'status' : MasteryStatus,
    'wrongCount' : IDL.Nat,
    'lastCorrect' : IDL.Int,
    'lastWrong' : IDL.Int,
    'masteryLevel' : IDL.Nat,
    'seenCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'lookupCount' : IDL.Nat,
    'vocabId' : IDL.Text,
    'lastSeen' : IDL.Int,
  });
  const ReadingSessionPublic = IDL.Record({
    'kanjiFailures' : IDL.Vec(IDL.Text),
    'wordsLookedUp' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'unknownWords' : IDL.Vec(IDL.Text),
  });
  const AdaptiveQuizRatio = IDL.Record({
    'kanjiPercent' : IDL.Nat,
    'vocabularyPercent' : IDL.Nat,
    'radicalPercent' : IDL.Nat,
  });
  const AdaptiveQuizSessionPublic = IDL.Record({
    'completedAt' : IDL.Opt(IDL.Int),
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'sessionId' : IDL.Text,
    'ratio' : AdaptiveQuizRatio,
  });
  
  return IDL.Service({
    'completeAdaptiveSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'getAllKanjiMastery' : IDL.Func([], [IDL.Vec(KanjiMastery)], ['query']),
    'getAllRadicalMastery' : IDL.Func([], [IDL.Vec(RadicalMastery)], ['query']),
    'getDokkaiPriorityKanji' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getKanjiDashboard' : IDL.Func([], [KanjiDashboardStats], ['query']),
    'getKanjiMastery' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(KanjiMasteryPublic)],
        ['query'],
      ),
    'getKanjiMasteryByChar' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(KanjiMastery)],
        ['query'],
      ),
    'getQuizAnalytics' : IDL.Func([], [QuizAnalytics], ['query']),
    'getRadicalDashboard' : IDL.Func([], [RadicalDashboardStats], ['query']),
    'getRadicalMastery' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RadicalMasteryPublic)],
        ['query'],
      ),
    'getRadicalMasteryByChar' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RadicalMastery)],
        ['query'],
      ),
    'getScoreSummary' : IDL.Func([], [ScoreSummary], ['query']),
    'getUntouchedKanji' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getVocabDashboard' : IDL.Func([], [VocabDashboardStats], ['query']),
    'getVocabMastery' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VocabMasteryPublic)],
        ['query'],
      ),
    'getWeakKanji' : IDL.Func([IDL.Nat], [IDL.Vec(WeakItem)], ['query']),
    'getWeakKanjiByThreshold' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(KanjiMastery)],
        ['query'],
      ),
    'getWeakRadicals' : IDL.Func([IDL.Nat], [IDL.Vec(WeakItem)], ['query']),
    'getWeakVocab' : IDL.Func([IDL.Nat], [IDL.Vec(WeakItem)], ['query']),
    'listKanjiMastery' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(KanjiMasteryPublic)],
        ['query'],
      ),
    'listReadingSessions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ReadingSessionPublic)],
        ['query'],
      ),
    'recordQuizResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'saveReadingSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'startAdaptiveSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [AdaptiveQuizSessionPublic],
        [],
      ),
    'trackKanjiCorrect' : IDL.Func([IDL.Text], [], []),
    'trackKanjiLookup' : IDL.Func([IDL.Text], [], []),
    'trackKanjiSeen' : IDL.Func([IDL.Text], [], []),
    'trackKanjiWrong' : IDL.Func([IDL.Text], [], []),
    'trackRadicalCorrect' : IDL.Func([IDL.Text], [], []),
    'trackRadicalSeen' : IDL.Func([IDL.Text], [], []),
    'trackRadicalWrong' : IDL.Func([IDL.Text], [], []),
    'trackVocabCorrect' : IDL.Func([IDL.Text], [], []),
    'trackVocabLookup' : IDL.Func([IDL.Text], [], []),
    'trackVocabSeen' : IDL.Func([IDL.Text], [], []),
    'trackVocabWrong' : IDL.Func([IDL.Text], [], []),
    'updateKanjiMastery' : IDL.Func([IDL.Text, IDL.Bool], [KanjiMastery], []),
    'updateRadicalMastery' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [RadicalMastery],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };